POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET  http://127.0.0.1:18080/api/qihao  HTTP/1.1


###
GET  http://iwuzhen.org:18070/api/qihao

###
# PUT http://127.0.0.1:18080/api/userdoubleboll HTTP/1.1
PUT http://iwuzhen.org:18070/api/userdoubleboll HTTP/1.1
content-type: application/json

[{
    "qihao": "20067",
    "redball": "1 3 7 21 27 32",
    "blueball": "09",
    "multiple": 1
},
{
    "qihao": "20064",
    "redball": "03 32 21 01 27 07 33",
    "blueball": "09 11",
    "multiple": 1
},
{
    "qihao": "20064",
    "redball": "11 32 21 01 24 07 33",
    "blueball": "03",
    "multiple": 1
}
]
###
Get http://127.0.0.1:18080/api/userdoubleboll HTTP/1.1

###
DELETE  http://127.0.0.1:18080/api/userdoubleboll HTTP/1.1
content-type: application/json

{
    "ID": 10
}


###
Get http://127.0.0.1:18080/api/jobrunner/json HTTP/1.1
