POST https://example.com/comments HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

###

GET  http://127.0.0.1:18080/api/qihao  HTTP/1.1

###
PUT http://127.0.0.1:18080/api/userdoubleboll HTTP/1.1
content-type: application/json

[{
    "qihao": "20067",
    "redball": "1 3 7 21 27 32",
    "blueball": "09",
    "multiple": 1
}
]
###
Get http://127.0.0.1:18080/api/userdoubleboll HTTP/1.1